---
abstract: 'HTTP::BrowserDetect integration for Mojolicious'
author:
  - 'Uwe Voelker <uwe@uwevoelker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-BrowserDetect
requires:
  HTTP::BrowserDetect: 0
version: 0.003
